//! Export the catalog to various formats.

use crate::catalog::Catalog;
use crate::types::RepoEntry;

/// Export the catalog as a Markdown table.
pub fn export_markdown(catalog: &Catalog) -> String {
    let mut out = String::from("| Repo | Language | Capabilities | Categories |\n");
    out.push_str("|------|----------|-------------|------------|\n");

    let mut repos: Vec<&RepoEntry> = catalog.repos().collect();
    repos.sort_by(|a, b| a.name.cmp(&b.name));

    for repo in &repos {
        let caps: Vec<&str> = repo.capabilities.iter().map(|c| c.name.as_str()).collect();
        let cats = repo.categories();
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            repo.name,
            repo.language,
            caps.join(", "),
            cats.join(", "),
        ));
    }

    out
}

/// Export the catalog as a JSON string.
pub fn export_json(catalog: &Catalog) -> String {
    let repos: Vec<&RepoEntry> = catalog.repos().collect();
    serde_json::to_string_pretty(&repos).unwrap_or_else(|e| format!("{{\"error\": \"{}\"}}", e))
}

/// Export the dependency graph in Graphviz DOT format.
pub fn export_dot(catalog: &Catalog) -> String {
    let mut out = String::from("digraph SuperInstance {\n");
    out.push_str("    rankdir=LR;\n");
    out.push_str("    node [shape=box, style=filled, fillcolor=lightyellow];\n\n");

    let mut repos: Vec<&RepoEntry> = catalog.repos().collect();
    repos.sort_by(|a, b| a.name.cmp(&b.name));

    for repo in &repos {
        out.push_str(&format!(
            "    \"{}\" [fillcolor={}];\n",
            repo.name,
            language_color(&repo.language)
        ));
    }

    out.push_str("\n");

    for repo in &repos {
        for dep in &repo.dependencies {
            out.push_str(&format!("    \"{}\" -> \"{}\";\n", repo.name, dep));
        }
    }

    out.push_str("}\n");
    out
}

/// Export SQL INSERT statements for Supabase seeding.
pub fn export_supabase_seed(catalog: &Catalog) -> String {
    let mut out = String::from("-- SuperInstance Catalog Seed Data\n");
    out.push_str("-- Auto-generated by si-catalog export_supabase_seed\n\n");

    // Repos table
    out.push_str("-- Repos\n");
    let mut repos: Vec<&RepoEntry> = catalog.repos().collect();
    repos.sort_by(|a, b| a.name.cmp(&b.name));

    for repo in &repos {
        out.push_str(&format!(
            "INSERT INTO repos (name, language) VALUES ('{}', '{}')\n  ON CONFLICT (name) DO UPDATE SET language = EXCLUDED.language;\n",
            repo.name, repo.language
        ));
    }

    out.push_str("\n-- Capabilities\n");

    for repo in &repos {
        for cap in &repo.capabilities {
            out.push_str(&format!(
                "INSERT INTO capabilities (name, category, provides, description, repo)\n  VALUES ('{}', '{}', '{}', '{}', '{}')\n  ON CONFLICT (name) DO UPDATE SET category = EXCLUDED.category, description = EXCLUDED.description;\n",
                escape_sql(&cap.name),
                escape_sql(&cap.category),
                escape_sql(&cap.provides),
                escape_sql(&cap.description),
                escape_sql(&cap.repo),
            ));
        }
    }

    out.push_str("\n-- Dependencies\n");

    for repo in &repos {
        for dep in &repo.dependencies {
            out.push_str(&format!(
                "INSERT INTO dependencies (repo, depends_on) VALUES ('{}', '{}');\n",
                repo.name, dep
            ));
        }
    }

    out
}

fn escape_sql(s: &str) -> String {
    s.replace('\'', "''")
}

fn language_color(lang: &str) -> &'static str {
    match lang.to_lowercase().as_str() {
        "rust" => "lightblue",
        "python" => "lightgreen",
        "typescript" => "plum",
        "javascript" => "wheat",
        "go" => "lightskyblue",
        _ => "lightyellow",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::default_catalog;

    #[test]
    fn markdown_contains_repos() {
        let cat = default_catalog();
        let md = export_markdown(&cat);
        assert!(md.contains("si-math"));
        assert!(md.contains("si-fleet"));
    }

    #[test]
    fn json_is_valid() {
        let cat = default_catalog();
        let json = export_json(&cat);
        let parsed: serde_json::Value = serde_json::from_str(&json).expect("invalid JSON");
        assert!(parsed.is_array());
    }

    #[test]
    fn dot_is_valid() {
        let cat = default_catalog();
        let dot = export_dot(&cat);
        assert!(dot.starts_with("digraph SuperInstance"));
        assert!(dot.contains("si-math"));
        assert!(dot.contains("->"));
    }

    #[test]
    fn supabase_has_inserts() {
        let cat = default_catalog();
        let sql = export_supabase_seed(&cat);
        assert!(sql.contains("INSERT INTO repos"));
        assert!(sql.contains("INSERT INTO capabilities"));
        assert!(sql.contains("INSERT INTO dependencies"));
    }
}
